// AIStill.ai — Nutritional Intelligence Hub
// Tier 2: AI Results Interpretation
// v1.0 | Built for Cloudflare Pages + Workers
// Auth integration point: search "AUTH STUB" for drop-in hooks

(function initReport(global, document) {
  'use strict';

  const DEFAULT_DISCLAIMER = 'This report is generated by an AI system for informational purposes only. It does not constitute a medical diagnosis, and should not replace consultation with a licensed healthcare provider. All findings should be reviewed with your physician before making any changes to your health regimen.';

  function redirectExpired() {
    global.location.replace('intake.html?reason=session_expired');
  }

  function normalizeStatus(status) {
    if (status === 'deficient' || status === 'borderline' || status === 'adequate') return status;
    return 'adequate';
  }

  function text(value, fallback = '') {
    return String(value || fallback);
  }

  function createElement(tag, className, content) {
    const element = document.createElement(tag);
    if (className) element.className = className;
    if (content !== undefined) element.textContent = content;
    return element;
  }

  function renderSummary(report) {
    const generatedTime = document.getElementById('generated-time');
    const overallStatus = document.getElementById('overall-status');
    const summaryText = document.getElementById('summary-text');
    const status = normalizeStatus(report.overallStatus);
    const generatedAt = report.generatedAt ? new Date(report.generatedAt) : null;

    generatedTime.textContent = generatedAt && !Number.isNaN(generatedAt.valueOf())
      ? `Generated ${generatedAt.toLocaleString()}`
      : 'Generated timestamp unavailable';
    overallStatus.className = `status-pill ${status}`;
    overallStatus.textContent = status;
    summaryText.textContent = text(report.summary, 'No summary was returned by the interpretation engine.');
  }

  function deficiencySort(a, b) {
    const order = { deficient: 0, borderline: 1 };
    return (order[a.severity] ?? 2) - (order[b.severity] ?? 2);
  }

  function renderDeficiencies(deficiencies) {
    const list = document.getElementById('deficiency-list');
    list.textContent = '';

    if (!deficiencies.length) {
      const empty = createElement('div', 'report-card', 'No deficient or borderline nutrients were returned. Discuss whether this matches the original panel with your healthcare provider.');
      list.append(empty);
      return;
    }

    deficiencies.sort(deficiencySort).forEach((item) => {
      const card = createElement('article', 'report-card');
      const header = createElement('div', 'report-card-header');
      const titleGroup = createElement('div');
      const title = createElement('h3', '', text(item.nutrient, 'Nutrient'));
      const category = createElement('p', 'hint', text(item.category, 'Category not specified'));
      const pill = createElement('span', `severity-pill ${normalizeStatus(item.severity)}`, text(item.severity, 'borderline'));
      const details = createElement('dl');

      titleGroup.append(title, category);
      header.append(titleGroup, pill);

      [
        ['Functional role', item.functionalRole],
        ['Clinical note', item.clinicalNote]
      ].forEach(([label, value]) => {
        const term = createElement('dt', '', label);
        const description = createElement('dd', '', text(value, 'Not provided. Discuss this finding with a licensed healthcare provider.'));
        details.append(term, description);
      });

      card.append(header, details);

      if (item.interactionFlag) {
        const callout = createElement('div', 'interaction-callout');
        callout.append(createElement('strong', '', 'Interaction'), createElement('span', '', text(item.interactionFlag)));
        card.append(callout);
      }

      list.append(card);
    });
  }

  function renderPatterns(patterns) {
    const section = document.getElementById('patterns-section');
    const list = document.getElementById('patterns-list');
    list.textContent = '';

    if (!patterns.length) {
      section.hidden = true;
      return;
    }

    section.hidden = false;
    patterns.forEach((pattern) => {
      const card = createElement('article', 'pattern-card');
      card.append(createElement('h3', '', text(pattern.patternName, 'Panel pattern')));
      card.append(createElement('p', '', text(pattern.interpretation, 'Pattern interpretation not provided.')));
      card.append(createElement('p', 'hint', text(pattern.clinicalContext, 'Discuss this pattern with a licensed healthcare provider.')));

      const chips = createElement('ul', 'chip-list');
      (Array.isArray(pattern.nutrients) ? pattern.nutrients : []).forEach((nutrient) => {
        chips.append(createElement('li', 'chip', text(nutrient)));
      });
      card.append(chips);
      list.append(card);
    });
  }

  function renderAdequate(nutrients) {
    const summary = document.getElementById('adequate-summary');
    const list = document.getElementById('adequate-list');
    list.textContent = '';
    summary.textContent = `Nutrients Within Functional Range (${nutrients.length})`;

    nutrients.forEach((nutrient) => {
      list.append(createElement('li', 'chip', text(nutrient)));
    });
  }

  function renderTalkingPoints(points) {
    const list = document.getElementById('talking-points-list');
    list.textContent = '';
    const safePoints = points.length ? points : ['Review whether these findings match your clinical history, medications, symptoms, and standard laboratory data.'];

    safePoints.forEach((point) => {
      const item = createElement('li');
      item.append(createElement('span', 'print-checkbox'), createElement('span', '', text(point)));
      list.append(item);
    });
  }

  function renderReport(report) {
    renderSummary(report);
    renderDeficiencies(Array.isArray(report.deficiencies) ? report.deficiencies : []);
    renderPatterns(Array.isArray(report.patterns) ? report.patterns : []);
    renderAdequate(Array.isArray(report.adequateNutrients) ? report.adequateNutrients : []);
    renderTalkingPoints(Array.isArray(report.providerTalkingPoints) ? report.providerTalkingPoints : []);
    document.getElementById('report-disclaimer').textContent = text(report.disclaimer, DEFAULT_DISCLAIMER);
  }

  const session = global.NIHSession.readSession();
  if (!session || global.NIHSession.isExpired(session) || !session.reportData) {
    redirectExpired();
    return;
  }

  renderReport(session.reportData);
})(window, document);
