// AIStill.ai — Nutritional Intelligence Hub
// Tier 2: AI Results Interpretation
// v1.0 | Built for Cloudflare Pages + Workers
// Auth integration point: search "AUTH STUB" for drop-in hooks

const SYSTEM_PROMPT = `
You are a clinical nutrition analyst assistant integrated into the
AIStill.ai Nutritional Intelligence Hub. Your role is to interpret
SpectraCell Micronutrient Test (MNT) results and produce a structured,
plain-language report for the patient and their healthcare provider.
Use an OsteopathicAI-aligned approach: augment clinical judgment, preserve
whole-person context, support relationship-centered communication, and make
the limits of the interpretation easy to review.

CRITICAL RULES — NEVER VIOLATE:
1. Do NOT diagnose any medical condition.
2. Do NOT tell the user to stop or change any medication.
3. Do NOT claim that any nutrient deficiency causes a specific disease.
4. Do NOT recommend specific supplement products, brands, or dosages.
5. Use "associated with" or "linked to" — never "causes" or "treats."
6. Always end every section with a recommendation to discuss findings
   with a licensed healthcare provider.
7. If the input does not appear to be a SpectraCell MNT result, return
   an error in the JSON: { "error": "unrecognized_format" }
8. Use optional patient context only to frame questions and patterns. Do not
   infer diagnoses, causes, or treatment plans from context fields.

PANEL CONTEXT:
SpectraCell MNT measures functional intracellular status of 31+
micronutrients including:
- Vitamins: A, B1, B2, B3, B6, B12, C, D, K, Biotin, Folate, Pantothenate
- Minerals: Calcium, Magnesium, Zinc, Copper, Manganese, Chromium
- Amino Acids: Asparagine, Glutamine, Serine
- Antioxidants: Alpha Lipoic Acid, CoQ10, Cysteine, Glutathione,
  Selenium, Vitamin E
- Fatty Acids: Oleic Acid
- Metabolites: Choline, Inositol, Carnitine
- Spectrox (Total Antioxidant Function)
- Immunidex (Immune Response Score)

Results are reported as % growth (functional), NOT serum concentration.
A result below the reference range indicates the cell is functionally
deficient — it cannot adequately use that nutrient even if serum levels
appear normal.

INTERPRETATION FRAMEWORK:
- Deficient: Flag clearly, explain functional role in plain language
- Borderline: Flag with context, note clinical significance where known
- Repletion notes: If two or more nutrients interact (e.g., Zinc + Copper,
  B12 + Folate, CoQ10 + statin use), note the interaction explicitly
- Pattern recognition: If 3+ deficiencies cluster in a functional category
  (e.g., multiple antioxidants low = oxidative stress pattern), name
  the pattern and explain it
- Whole-person framing: When context is provided, briefly explain how symptoms,
  sleep, stress, activity, nutrition pattern, medications, goals, or patient
  questions should shape the provider conversation without making unsupported
  claims.

OUTPUT FORMAT — return ONLY valid JSON, no markdown, no preamble:
{
  "summary": string (2-3 sentences, plain language overview),
  "wholePersonContext": string (1-3 sentences describing how available
    context should shape the provider conversation, or an empty string if
    no meaningful context was provided),
  "overallStatus": "deficient" | "borderline" | "adequate",
  "deficiencies": [
    {
      "nutrient": string,
      "category": string,
      "severity": "deficient" | "borderline",
      "functionalRole": string (1-2 sentences, plain language),
      "clinicalNote": string (what this may be associated with,
                     careful language, no diagnostic claims),
      "interactionFlag": string | null (note if this nutrient
                        interacts with another finding or medication)
    }
  ],
  "patterns": [
    {
      "patternName": string,
      "nutrients": [string],
      "interpretation": string,
      "clinicalContext": string
    }
  ],
  "adequateNutrients": [string],
  "providerTalkingPoints": [string] (3-5 questions or bullet points the
                            patient can bring to their doctor),
  "disclaimer": "This report is generated by an AI system for
    informational purposes only. It does not constitute a medical
    diagnosis, and should not replace consultation with a licensed
    healthcare provider. All findings should be reviewed with your
    physician before making any changes to your health regimen.",
  "generatedAt": ISO timestamp
}
`;

const DISCLAIMER = 'This report is generated by an AI system for informational purposes only. It does not constitute a medical diagnosis, and should not replace consultation with a licensed healthcare provider. All findings should be reviewed with your physician before making any changes to your health regimen.';
const RATE_LIMIT_WINDOW_SECONDS = 60 * 60;
const RATE_LIMIT_MAX = 10;

export default {
  async fetch(request, env, context) {
    const url = new URL(request.url);

    if (request.method === 'OPTIONS') {
      return withCors(new Response(null, { status: 204 }));
    }

    if (request.method !== 'POST' || url.pathname !== '/api/interpret') {
      return json({ error: 'not_found' }, 404);
    }

    // AUTH HOOK — when auth is implemented, validate JWT here before
    // processing. Extract userId, attach to log entry, store report
    // to user's record in D1 database.
    const sessionId = crypto.randomUUID();
    let payload;

    try {
      payload = await request.json();
    } catch (error) {
      return json({ error: 'invalid_json' }, 400);
    }

    const requestSessionId = sanitizeLogToken(payload.sessionId) || sessionId;
    const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
    const rateLimit = await enforceRateLimit(env, ip);
    if (!rateLimit.allowed) {
      logRequest(context, { sessionId: requestSessionId, status: 'rate_limited' });
      return json({ error: 'rate_limited' }, 429);
    }

    const rawContent = sanitizeText(payload.rawContent);
    const intakeContext = sanitizeContext(payload.context || {});

    if (!rawContent) {
      return json({ error: 'missing_raw_content' }, 400);
    }

    if (!env.AI_ENDPOINT || !env.AI_MODEL_ID) {
      logRequest(context, { sessionId: requestSessionId, status: 'config_missing' });
      return json({ error: 'config_missing' }, 500);
    }

    try {
      const modelText = await callModel(env, rawContent, intakeContext);
      const report = parseModelJson(modelText);

      if (report.error === 'unrecognized_format') {
        logRequest(context, { sessionId: requestSessionId, status: 'unrecognized_format' });
        return json(report, 200);
      }

      const validated = validateReport(report);
      logRequest(context, { sessionId: requestSessionId, status: 'ok' });
      return json(validated, 200);
    } catch (error) {
      const status = error.message === 'parse_failure' ? 'parse_failure' : 'model_failure';
      logRequest(context, { sessionId: requestSessionId, status });
      return json({ error: status }, 500);
    }
  }
};

function sanitizeText(value) {
  return String(value || '')
    .replace(/<[^>]*>/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim()
    .slice(0, 120000);
}

function sanitizeLogToken(value) {
  const token = String(value || '').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 80);
  return token || null;
}

function sanitizeContext(context) {
  return {
    activityLevel: sanitizeText(context.activityLevel).slice(0, 80),
    ageRange: sanitizeText(context.ageRange).slice(0, 20),
    clinicianQuestions: sanitizeText(context.clinicianQuestions).slice(0, 1200),
    currentlySupplementing: typeof context.currentlySupplementing === 'boolean'
      ? context.currentlySupplementing
      : null,
    medications: sanitizeText(context.medications).slice(0, 4000),
    nutritionPattern: sanitizeText(context.nutritionPattern).slice(0, 1200),
    primaryConcern: sanitizeText(context.primaryConcern).slice(0, 80),
    sleepRecovery: sanitizeText(context.sleepRecovery).slice(0, 80),
    stressLoad: sanitizeText(context.stressLoad).slice(0, 80),
    currentlySupplemening: typeof context.currentlySupplemening === 'boolean'
      ? context.currentlySupplemening
      : null
  };
}

async function enforceRateLimit(env, ip) {
  if (!env.RATE_LIMIT) {
    return { allowed: true, count: 0 };
  }

  const key = `interpret:${ip}`;
  const current = Number(await env.RATE_LIMIT.get(key)) || 0;
  if (current >= RATE_LIMIT_MAX) {
    return { allowed: false, count: current };
  }

  await env.RATE_LIMIT.put(key, String(current + 1), { expirationTtl: RATE_LIMIT_WINDOW_SECONDS });
  return { allowed: true, count: current + 1 };
}

async function callModel(env, rawContent, context) {
  const messages = [
    { role: 'system', content: SYSTEM_PROMPT.trim() },
    {
      role: 'user',
      content: JSON.stringify({
        task: 'Interpret this SpectraCell Micronutrient Test result.',
        rawContent,
        context
      })
    }
  ];

  const response = await fetch(env.AI_ENDPOINT, {
    method: 'POST',
    headers: buildHeaders(env),
    body: JSON.stringify({
      model: env.AI_MODEL_ID,
      messages,
      temperature: 0.2,
      response_format: { type: 'json_object' }
    })
  });

  if (!response.ok) {
    throw new Error('model_failure');
  }

  const body = await response.json();
  return extractModelText(body);
}

function buildHeaders(env) {
  const headers = { 'Content-Type': 'application/json' };
  if (env.AI_API_KEY) {
    headers.Authorization = `Bearer ${env.AI_API_KEY}`;
  }
  return headers;
}

function extractModelText(body) {
  if (typeof body === 'string') return body;
  if (typeof body.output === 'string') return body.output;
  if (typeof body.content === 'string') return body.content;
  if (body.message && typeof body.message.content === 'string') return body.message.content;
  if (Array.isArray(body.choices) && body.choices[0]?.message?.content) {
    return body.choices[0].message.content;
  }
  throw new Error('parse_failure');
}

function parseModelJson(modelText) {
  const trimmed = String(modelText || '').trim();
  const first = trimmed.indexOf('{');
  const last = trimmed.lastIndexOf('}');
  if (first === -1 || last === -1 || last <= first) {
    throw new Error('parse_failure');
  }

  try {
    return JSON.parse(trimmed.slice(first, last + 1));
  } catch (error) {
    throw new Error('parse_failure');
  }
}

function validateReport(report) {
  if (!report || typeof report !== 'object') {
    throw new Error('parse_failure');
  }

  const status = ['deficient', 'borderline', 'adequate'].includes(report.overallStatus)
    ? report.overallStatus
    : 'borderline';

  return {
    summary: stringOrFallback(report.summary, 'The panel was interpreted, but the model did not return a complete summary. Review the full findings with a licensed healthcare provider.'),
    wholePersonContext: stringOrFallback(report.wholePersonContext, ''),
    overallStatus: status,
    deficiencies: arrayOrEmpty(report.deficiencies).map(validateDeficiency),
    patterns: arrayOrEmpty(report.patterns).map(validatePattern),
    adequateNutrients: arrayOrEmpty(report.adequateNutrients).map((item) => stringOrFallback(item, 'Unspecified nutrient')),
    providerTalkingPoints: arrayOrEmpty(report.providerTalkingPoints).slice(0, 5).map((item) => stringOrFallback(item, 'Discuss this finding with your healthcare provider.')),
    disclaimer: DISCLAIMER,
    generatedAt: report.generatedAt || new Date().toISOString()
  };
}

function validateDeficiency(item) {
  const severity = ['deficient', 'borderline'].includes(item?.severity) ? item.severity : 'borderline';
  return {
    nutrient: stringOrFallback(item?.nutrient, 'Unspecified nutrient'),
    category: stringOrFallback(item?.category, 'Unspecified category'),
    severity,
    functionalRole: stringOrFallback(item?.functionalRole, 'Functional role not provided. Discuss this finding with a licensed healthcare provider.'),
    clinicalNote: stringOrFallback(item?.clinicalNote, 'Clinical context not provided. Discuss this finding with a licensed healthcare provider.'),
    interactionFlag: item?.interactionFlag ? stringOrFallback(item.interactionFlag, null) : null
  };
}

function validatePattern(item) {
  return {
    patternName: stringOrFallback(item?.patternName, 'Panel pattern'),
    nutrients: arrayOrEmpty(item?.nutrients).map((nutrient) => stringOrFallback(nutrient, 'Unspecified nutrient')),
    interpretation: stringOrFallback(item?.interpretation, 'Pattern interpretation not provided. Discuss this with a licensed healthcare provider.'),
    clinicalContext: stringOrFallback(item?.clinicalContext, 'Review this pattern with a licensed healthcare provider.')
  };
}

function arrayOrEmpty(value) {
  return Array.isArray(value) ? value : [];
}

function stringOrFallback(value, fallback) {
  if (value === null && fallback === null) return null;
  const text = String(value || '').trim();
  return text || fallback;
}

function logRequest(context, entry) {
  const logEntry = {
    sessionId: entry.sessionId,
    status: entry.status,
    timestamp: new Date().toISOString()
  };
  context.waitUntil(Promise.resolve(console.log(JSON.stringify(logEntry))));
}

function json(payload, status = 200) {
  return withCors(new Response(JSON.stringify(payload), {
    status,
    headers: { 'Content-Type': 'application/json; charset=utf-8' }
  }));
}

function withCors(response) {
  const headers = new Headers(response.headers);
  headers.set('Access-Control-Allow-Origin', '*');
  headers.set('Access-Control-Allow-Methods', 'POST, OPTIONS');
  headers.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}
